project_id = "yajpeseecldrlvqujkjc"

[functions.analyze-item]
verify_jwt = false

[functions.ebay-pricing]
verify_jwt = false

[functions.ebay-publish]
verify_jwt = false

[functions.spot-prices]
verify_jwt = false

[functions.transcribe-voice]
verify_jwt = false

[functions.ebay-listings]
verify_jwt = false