-- Migration: Competitor prices — Gemini query enhancement + 8-hour cache TTL
-- 
-- Changes:
--   1. Add gemini_search_query column to store the Gemini-optimised search string
--      (distinct from the heuristic deriveSearchQuery result stored in search_query)
--   2. Reduce expires_at default from 25 hours → 8 hours so stale data ages out
--      faster and the cron / manual refresh cycles feel more up-to-date
--   3. Add fetched_at index hint for the 8-hour cache-check query pattern used
--      in ebay-competitor-search and the cron job

-- 1. Gemini-generated search query column
ALTER TABLE competitor_prices
  ADD COLUMN IF NOT EXISTS gemini_search_query TEXT;

COMMENT ON COLUMN competitor_prices.gemini_search_query IS
  'eBay search query generated by Gemini Flash from the listing title. '
  'More focused than the heuristic search_query — strips noise words and '
  'adds domain-specific qualifiers. NULL if Gemini was unavailable.';

-- 2. Reduce default TTL to 8 hours
--    (existing rows keep their old expires_at; only new inserts get 8h)
ALTER TABLE competitor_prices
  ALTER COLUMN expires_at SET DEFAULT (NOW() + INTERVAL '8 hours');

COMMENT ON COLUMN competitor_prices.expires_at IS
  'Row expires 8 hours after creation. Cron deletes expired rows before each run.';

-- 3. Partial index to speed up "find listings with stale/no cache" query in cron
CREATE INDEX IF NOT EXISTS idx_competitor_prices_user_fetched
  ON competitor_prices (user_id, fetched_at DESC);